### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by calvarez-ov** [Genymobile/gm_pr#21]
See if anything can be done to speed up the loading of the webpage.

It takes about 10-15 seconds to load the following (each): 

A project with one repo, 4 pull requests, 18 comments

A project with 3 repos, 8 pull requests, 87 comments

**Comment by CedricCabessa** [comment]
we do a lot of request. a ~15 sec delay is not crazy I think
Closing now
If someone want to reopen, please provide a comparative time using another language/tool/...: eg how many time with curl (beware that some requests depends on the other)
This way we can have a more precise target to know how much we can optimize
