### ISSUE TITLE
"Back to project list" doesn't direct to project list

### ISSUE THREAD

**Issue by amasciulli** [Genymobile/gm_pr#63]
Same as #58 . Thought I had fixed it, but seems like I hadn't.

**Comment by CedricCabessa** [comment]
seem to work in prod...

**Comment by amasciulli** [comment]
Not for me it doesn't

**Comment by amasciulli** [comment]
problem identified : you come from http://jenkins.genymobile.com/gm_pr it doesn't work, but it does if you come from http://jenkins.genymobile.com/gm_pr/ . URL mapping must be fixed, or better it should be redefined

**Comment by CedricCabessa** [comment]
Let's be lazy and say we don't support "suburl" (like https://mydomain/gm_pr) but only gmpr.mydomain
it is a mess with django (surprisingly, it should be a basic feature imho) but everything works better since we switched to gmpr.genymobile.com
We will reopen if user complains
