### ISSUE TITLE
Change LGTM column to "Approvals"

### ISSUE THREAD

**Issue by qfarizon** [Genymobile/gm_pr#81]
With the new Github PR workflow (https://help.github.com/articles/about-pull-request-reviews/ ) we can now formally approve a PR.
gm_pr should take that into account, and count approvals instead of LGTM
I propose to count only approvals and drop LGTM parsing completely.

API reference (not yet stable) https://developer.github.com/v3/projects/

**Comment by calvarez-ov** [comment]
The idea sounds great to me.  In our project we don't use the github "review" feature yet (just comments for now), but we don't use LGTM either :)

**Comment by fbarthelery** [comment]
I looked at the API today and it does not seems to contains anything related to pull request approval. But maybe I did not look right.

**Comment by CedricCabessa** [comment]
I've contacted github support, they told me it's planned but no ETA.
We should watch https://developer.github.com/changes/ for more info (it's in my rss ;-) )

**Comment by CedricCabessa** [comment]
https://github.com/Genymobile/gm_pr/pull/82
